"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require("express");
var userController = require("./controllers/user");
var app = express();
app.get('/api/user/:userId', userController.user);
app.get('/api/user/:userId/avatar', userController.getUserAvatar);
app.delete('/api/user/:userId/avatar', userController.deleteuserAvatar);
userController.cronGetUsers();
app.listen(3000);
